proxies:
  - {name: opentunnel.net-razz, server: 104.17.2.81, port: 443, type: vless, uuid: 4f17e173-4af9-5041-9662-f6c27e0decfd, cipher: auto, tls: true, skip-cert-verify: true, servername: api.midtrans.com, network: ws, ws-opts: {path: "ws://api.midtrans.com/opentunnel?user=opentunnel.net-razz", headers: {Host: idx-1.openv2ray.com}}, udp: true}
  - {name: sg1.vless.co, server: 104.17.2.81, port: 443, type: vless, uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5, cipher: auto, tls: true, skip-cert-verify: true, servername: api.midtrans.com, network: ws, ws-opts: {path: ws://api.midtrans.com/fastssh/razz/62fb33f608883/, headers: {Host: sg1.vless.co}}, udp: true}
  - {name: sxtcp-admin, server: 104.17.2.81, port: 443, type: vmess, uuid: e4134d12-c932-40b1-a68d-0039cdaefef1, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: api.midtrans.com, network: ws, ws-opts: {path: ws://api.midtrans.com/herbalserver, headers: {Host: sgf-1.herbalv2ray.me}}, udp: true}
  - {name: vless-ws-tls, server: 104.17.2.81, port: 443, type: vless, uuid: 5b1fb8be-da9f-436a-a33a-18a5343567b7, cipher: auto, tls: true, skip-cert-verify: true, servername: api.midtrans.com, network: ws, ws-opts: {path: ws://api.midtrans.com/vless, headers: {Host: sg2-full.privateip.net}}, udp: true}
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - opentunnel.net-razz
      - sg1.vless.co
      - sxtcp-admin
      - vless-ws-tls
      - LOAD-BALANCE
      - DIRECT
  - name: LOAD-BALANCE
    type: load-balance
    strategy: round-robin
    url: http://hi.bonds.id/ping
    interval: 300
    proxies:
      - opentunnel.net-razz
      - sg1.vless.co
      - sxtcp-admin
      - vless-ws-tls
rules:
  - MATCH,LOAD-BALANCE
