proxies:
  - {name: sxtcp-owner0, server: 104.17.2.81, port: 443, type: vmess, uuid: 5d452c53-2c9b-487e-a644-9bf1c8251e6f, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: api.midtrans.com, network: ws, ws-opts: {path: wss://api.midtrans.com/herbalserver, headers: {Host: sgdo-1.herbalv2ray.me}}, udp: true}
  - {name: vless-ws-tls0, server: 104.17.2.81, port: 443, type: vless, uuid: 8e093141-f639-4ba0-9444-bc259d970ec4, cipher: auto, tls: true, skip-cert-verify: true, servername: api.midtrans.com, network: ws, ws-opts: {path: wss://api.midtrans.com/vless, headers: {Host: sg2-full.privateip.net}}, udp: true}
  - {name: sg2.vless.co0, server: 104.17.2.81, port: 443, type: vless, uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5, cipher: auto, tls: true, skip-cert-verify: true, servername: api.midtrans.com, network: ws, ws-opts: {path: wss://api.midtrans.com/fastssh/razxx/63038ddc03c70/, headers: {Host: sg2.vless.co}}, udp: true}
  - {name: sxtcp-owner, server: 104.22.24.131, port: 443, type: vmess, uuid: 5d452c53-2c9b-487e-a644-9bf1c8251e6f, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: sgdo-1.herbalv2ray.me, network: ws, ws-opts: {path: /herbalserver, headers: {Host: sgdo-1.herbalv2ray.me}}, udp: true}
  - {name: vless-ws-tls, server: 104.22.24.131, port: 443, type: vless, uuid: 8e093141-f639-4ba0-9444-bc259d970ec4, cipher: auto, tls: true, skip-cert-verify: true, servername: sg2-full.privateip.net, network: ws, ws-opts: {path: /vless, headers: {Host: sg2-full.privateip.net}}, udp: true}
  - {name: sg2.vless.co, server: 104.22.24.131, port: 443, type: vless, uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5, cipher: auto, tls: true, skip-cert-verify: true, servername: sg2.vless.co, network: ws, ws-opts: {path: /fastssh/razxx/63038ddc03c70/, headers: {Host: sg2.vless.co}}, udp: true}
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - sxtcp-owner0
      - vless-ws-tls0
      - sg2.vless.co0
      - sxtcp-owner
      - vless-ws-tls
      - sg2.vless.co
      - LOAD-BALANCE
      - DIRECT
  - name: LOAD-BALANCE
    type: load-balance
    strategy: round-robin
    url: http://hi.bonds.id/ping
    interval: 300
    proxies:
      - sxtcp-owner0
      - vless-ws-tls0
      - sg2.vless.co0
      - sxtcp-owner
      - vless-ws-tls
      - sg2.vless.co
rules:
  - MATCH,LOAD-BALANCE
