proxies:
  - {name: backVIp0, server: 104.17.2.81, port: 443, type: trojan, password: 8bcdef7c-f118-4763-b452-dfe8710be239, skip-cert-verify: true, sni: api.midtrans.com, network: ws, ws-opts: {path: wss://api.midtrans.com/buy-trojan-pm-telegram-at-synricha, headers: {Host: simp.apasih.id}}, udp: true}
  - {name: TJ-Jagoan0, server: 104.17.2.81, port: 443, type: trojan, password: vvip-kasrun123, skip-cert-verify: true, sni: api.midtrans.com, network: ws, ws-opts: {path: ws://api.midtrans.com/trojan, headers: {Host: sg2tr.jagoan.vip}}, udp: true}
  - {name: TJ_iptun_0, server: 104.17.2.81, port: 443, type: trojan, password: razz00123123, skip-cert-verify: true, sni: api.midtrans.com, network: ws, ws-opts: {path: ws://api.midtrans.com/buy-trojan-ws-pm-telegram-at-synricha, headers: {Host: nginx-rc-173.apasih.id}}, udp: true}
  - {name: backVIp, server: 104.22.24.131, port: 443, type: trojan, password: 8bcdef7c-f118-4763-b452-dfe8710be239, skip-cert-verify: true, sni: simp.apasih.id, network: ws, ws-opts: {path: /buy-trojan-pm-telegram-at-synricha, headers: {Host: simp.apasih.id}}, udp: true}
  - {name: TJ-Jagoan, server: 104.22.24.131, port: 443, type: trojan, password: vvip-kasrun123, skip-cert-verify: true, sni: sg2tr.jagoan.vip, network: ws, ws-opts: {path: /trojan, headers: {Host: sg2tr.jagoan.vip}}, udp: true}
  - {name: TJ_iptun, server: 104.22.24.131, port: 443, type: trojan, password: razz00123123, skip-cert-verify: true, sni: nginx-rc-173.apasih.id, network: ws, ws-opts: {path: /buy-trojan-ws-pm-telegram-at-synricha, headers: {Host: nginx-rc-173.apasih.id}}, udp: true}
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - backVIp0
      - TJ-Jagoan0
      - TJ_iptun_0
      - backVIp
      - TJ-Jagoan
      - TJ_iptun
      - FALLBACK
      - DIRECT
  - name: FALLBACK
    type: fallback
    url: http://hi.bonds.id/ping
    interval: 300
    proxies:
      - backVIp0
      - TJ-Jagoan0
      - TJ_iptun_0
      - backVIp
      - TJ-Jagoan
      - TJ_iptun
rules:
  - MATCH,FALLBACK
